- name: Enable and start Grafana service
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: Create provisioning directory
  file:
    path: /etc/grafana/provisioning/datasources
    state: directory
    owner: root
    group: root

- name: Configure Grafana with admin credentials
  copy:
    dest: /etc/grafana/grafana.ini
    content: |
      [security]
      admin_user = {{ grafana.admin_user }}
      admin_password = {{ grafana.admin_password }}

# Upload Prometheus datasource configuration
- name: Upload Prometheus datasource config to Grafana
  template:
    src: prometheus-datasource.yml.j2
    dest: /etc/grafana/provisioning/datasources/prometheus-datasource.yml
    owner: root
    group: root
    mode: '0644'
  notify:
  - Restart Grafana

- name: Import Grafana dashboard by ID at root level
  community.grafana.grafana_dashboard:
    grafana_url: "{{ grafana.grafana_url }}"
    grafana_user: "{{ grafana.admin_user }}"
    grafana_password: "{{ grafana.admin_password }}"
    dashboard_id: "{{ grafana.dashboard_id }}"
    overwrite: "{{ grafana.dashboard_overwrite }}"
    folder: "{{ grafana.folder }}"
    validate_certs: false
