- name: Install Ansible and required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
  - ansible
  - zip
  - unzip

- name: Remove NSO_A2.zip in bastion
  file:
    path: /opt/NSO_A2.zip
    state: absent

- name: Remove NSO_A2 directory in bastion
  file:
    path: /opt/NSO_A2
    state: absent
    recurse: yes
  ignore_errors: yes


- name: Copy Ansible folder to bastion
  copy:
    src: NSO_A2.zip
    dest: /opt/
    owner: root
    group: root
    mode: '0755'


- name: Unzip the archive
  unarchive:
    src: /opt/NSO_A2.zip
    dest: /opt/
    remote_src: yes
    extra_opts: ['-j']


- name: Print bastion and proxy IP addresses
  debug:
    msg:
    - "hallo"



